import type { Metadata } from "next";
import "./globals.css";
import { Footer, Navbar } from "../components";

export const metadata: Metadata = {
  title: "Car Dealer App",
  description: "Generated by create next app",
  icons: [{ url: "/favicon.ico", rel: "icon" }],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="relative">
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
